# Generated by Django 4.0.5 on 2022-07-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together={('user_id', 'flight')},
        ),
    ]
